x-logging: &logging
  driver: "json-file"
  options:
    max-size: "16m"
    max-file: "16"

#include: TODO: configure traefik launch with an optional service launch in case of traefik is running
#  - docker-compose-traefik.yml
services:
  stackly-postgres:
    image: postgres
    container_name: stackly-postgres
    hostname: stackly-postgres
    restart: always
    environment:
      POSTGRES_DB: stackly # TODO: change to the actual database name from the env file
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    
    ports:
      - "5433:5432"
    
    networks:
      - stackly-network

    volumes:
      - stackly-postgres-data:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 2s
      retries: 20

    logging:
      options:
        max-size: "10m"
        max-file: "3"

  db-init-migrate:
    image: node:22-alpine
    container_name: db-init-migrate
    restart: always
    command: npx prisma migrate dev --name init --schema=/app/prisma/schema.prisma # TODO: copy Prisma schema from repository to the host
    environment:
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@stackly-postgres:5432/stackly?schema=public # TODO: change to the actual database name from the env file
    depends_on:
      stackly-postgres:
        condition: service_healthy
    
    profiles:
      - manual
    
    volumes:
      - ./${DOMAIN}/prisma:/app/prisma # TODO: copy Prisma schema from repository to the host

    networks:
      - stackly-network

  stackly-app:
    container_name: ${ALIAS}
    image: ghcr.io/${IMAGE_NAME}:latest
    pull_policy: always

    logging: *logging
    restart: unless-stopped

    ports:
      - "${APP_PORT}:3000"

    depends_on:
      stackly-postgres:
        condition: service_healthy
    
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    
    labels:
      - traefik.enable=true
      - traefik.http.routers.${ALIAS}.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.${ALIAS}.entrypoints=https
      - traefik.http.routers.${ALIAS}.tls.certresolver=letsencrypt
      - traefik.http.services.${ALIAS}.loadbalancer.server.port=${APP_PORT}

    networks:
      - stackly-network
      - traefik

volumes:
  stackly-postgres-data:
    name: stackly-postgres-data

networks:
  stackly-network:
    name: stackly-network
  traefik:
    name: traefik
    external: true