x-logging: &logging
  driver: "json-file"
  options:
    max-size: "16m"
    max-file: "16"

include: 
  - traefik.yml

services:
  nextapp:
    container_name: ${ALIAS}
    image: ghcr.io/${IMAGE_NAME}:latest
    pull_policy: always

    logging: *logging
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "${APP_PORT}:3000"

    labels:
      - traefik.enable=true
      - traefik.http.routers.${ALIAS}.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.${ALIAS}.entrypoints=https
      - traefik.http.routers.${ALIAS}.tls.certresolver=letsencrypt
      - traefik.http.services.${ALIAS}.loadbalancer.server.port=${APP_PORT}

    networks:
      - traefik
      - database
    
    db:
      image: postgres
      container_name: stackly-db
      restart: always
      environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: stackly

networks:
  database:
  traefik:
    external:
      name: traefik
