version: "3.5"

services:
  https:
    image: traefik:v2.6.1
    command:
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik"
      - "--accesslog=true"

      - "--entrypoints.http-back.address=:80"
      - "--entrypoints.https.address=:443"

      - "--serverstransport.insecureskipverify=true"

      - "--entrypoints.http-back.http.redirections.entrypoint.to=https"

      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http-back"
      - "--certificatesresolvers.letsencrypt.acme.email=${LE_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"

    labels:
      traefik.enable: "true"
      traefik.http.services.http-back.loadbalancer.server.port: "80"

      traefik.http.routers.http-back.service: http-back
      traefik.http.routers.http-back.rule: "HostRegexp(`{any:.*}`) && PathPrefix(`/.well-known/acme-challenge/`)"
      traefik.http.routers.http-back.priority: "100500"
      traefik.http.routers.http-back.entrypoints: http

      traefik.http.routers.http-redirect-https.service: http-back
      traefik.http.routers.http-redirect-https.rule: "HostRegexp(`{any:.*}`)"
      traefik.http.routers.http-redirect-https.priority: "0"
      traefik.http.routers.http-redirect-https.entrypoints: http

    ports:
      - 443:443

    logging:
      driver: json-file
      options:
        max-size: "16m"
        max-file: "16"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt:/letsencrypt

    restart: unless-stopped

    networks:
      - traefik

  http:
    image: traefik:v2.6.1
    command:
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik"
      - "--accesslog=true"

      - "--entrypoints.http.address=:80"

      - "--serverstransport.insecureskipverify=true"

    ports:
      - 80:80

    logging:
      driver: json-file
      options:
        max-size: "16m"
        max-file: "16"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

    restart: unless-stopped

    networks:
      - traefik

volumes:
  letsencrypt:

networks:
  traefik:
    name: traefik
