name: Build and deploy the app

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      
      - name: 'Create env file'
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  
  configuration:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout into main
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Configure SSH
        uses: ./.github/actions/ssh
        with:
          ssh_user: ${{ vars.HOST_PROD_USER }}
          ssh_key: ${{ secrets.DEPLOY_SSH_SECRET_KEY }}
          ssh_host: ${{ vars.HOST_PROD_IP }}

      - name: Create and upload ENV file and docker compose file to the server
        uses: ./.github/actions/docker-compose-config
        with:
          domain: ${{ vars.DOMAIN }}
          app_port: ${{ vars.APP_PORT }}
          image_name: ${{ env.IMAGE_NAME }}
          postgres_password: ${{ secrets.POSTGRES_PASSWORD }}
          alias: ${{ vars.ALIAS }}
          le_email: ${{ vars.LE_EMAIL }}
          host_prod_service_path: ${{ vars.HOST_PROD_SERVICE_PATH }}
  
  db-migration:
    runs-on: ubuntu-latest
    needs: configuration

    steps:
      - name: Run the db migration
        run: ssh prod docker compose run --rm db-init-migrate

  deploy:
    runs-on: ubuntu-latest
    needs: db-migration

    steps:
      - name: Run the app container
        run: ssh prod docker compose --env-file ${{ vars.HOST_PROD_SERVICE_PATH }}/${{ vars.DOMAIN }}.env -f ${{ vars.HOST_PROD_SERVICE_PATH }}/${{ vars.DOMAIN }}.yml up -d
